openapi: 3.0.1
info:
  title: DocuMender
  description: A ChatGPT plugin to facilitate writing of long publication documents.
  version: 'v1'
servers:
  - url: http://localhost:3000
paths:
  /section:
    post:
      summary: Create a new section
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                path:
                  type: string
                name:
                  type: string
                content:
                  type: string
      responses:
        "201":
          description: Section created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  section:
                    $ref: '#/components/schemas/Section'
        "404":
          description: Parent section not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /section/{path}:
    put:
      summary: Update a section
      parameters:
        - in: path
          name: path
          schema:
            type: string
          required: true
          description: The path of the section to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
      responses:
        "200":
          description: Section updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  section:
                    $ref: '#/components/schemas/Section'
        "404":
          description: Section not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    delete:
      summary: Delete a section
      parameters:
        - in: path
          name: path
          schema:
            type: string
          required: true
          description: The path of the section to delete
      responses:
        "200":
          description: Section deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "404":
          description: Section not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    get:
      summary: Get a section
      parameters:
        - in: path
          name: path
          schema:
            type: string
          required: true
          description: The path of the section to get
      responses:
        "200":
          description: Section found
          content:
            application/json:
              schema:
                type: object
                properties:
                  section:
                    $ref: '#/components/schemas/Section'
        "404":
          description: Section not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /section/move:
    patch:
      summary: Move a section
      # Define requestBody, and responses for the moveSection endpoint
  /save:
    post:
      summary: Save the document
      # Define requestBody, and responses for the saveDocument endpoint
components:
  schemas:
    Section:
      type: object
      properties:
        name:
          type: string
       
